kafka:
  brokers:
    - localhost:9092
  topic: task-queue-topic

redis:
  address: localhost:6379
  password: ""
  db: 0

postgres:
  dsn: postgres://youruser:yourpassword@localhost:5432/yourdb?sslmode=disable